# Generated by Django 5.2.7 on 2026-01-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='primer_login',
            field=models.BooleanField(default=True, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión.'),
        ),
        migrations.AlterField(
            model_name='registrovacaciones',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
