# Generated by Django 5.2.7 on 2026-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_empleado_primer_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(help_text='Ej: tu-email@gmail.com', max_length=200)),
                ('email_host_password', models.CharField(help_text='Contraseña de aplicación', max_length=200)),
                ('emails_notificacion', models.TextField(help_text='Emails separados por coma (,) que recibirán avisos de nuevas solicitudes.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
