# Generated by Django 5.2.7 on 2026-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_configuracionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionemail',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Usar SSL Directo (Puerto 465)'),
        ),
        migrations.AlterField(
            model_name='configuracionemail',
            name='email_host',
            field=models.CharField(default='mail.tudominio.com', help_text='Ej: mail.tudominio.com o cXXXX.ferozo.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionemail',
            name='email_host_password',
            field=models.CharField(help_text='Contraseña de la cuenta de correo', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionemail',
            name='email_host_user',
            field=models.CharField(help_text='Ej: info@tudominio.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionemail',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar STARTTLS (Puerto 587)'),
        ),
    ]
