# Generated by Django 5.2.7 on 2026-01-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_configuracionemail_options_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sistema', to='gestion.registrovacaciones'),
        ),
    ]
