# Generated by Django 5.2.7 on 2026-01-08 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_notificacion_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('db', 'Base de Datos'), ('code', 'Código Fuente'), ('full', 'Completo')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.CharField(blank=True, max_length=500)),
                ('tamaño', models.BigIntegerField(default=0, help_text='Tamaño en bytes')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('commit_hash', models.CharField(blank=True, help_text='Hash del commit de Git', max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
