# Generated by Django 5.2.7 on 2026-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='tipo',
            field=models.CharField(choices=[('db', 'Base de Datos'), ('code', 'Código Fuente (ZIP)'), ('github', 'Sincronización GitHub'), ('full', 'Completo')], max_length=10),
        ),
    ]
